### ISSUE TITLE
Undocumented return value from HPack.decode/2

### ISSUE THREAD

**Issue by mtrudel** [OleMchls/elixir-hpack#16] opened 2021-05-24 18:04 UTC
While attempting to write a test for [bandit](/mtrudel/bandit) covering behaviour in the case where we are unable to decompress a header block fragment, I came across an undocumented return value from `HPack.decode/2`:

```elixir
iex(1)> ctx = HPack.Table.new(1000)
%HPack.Table{size: 1000, table: []}
iex(2)> HPack.decode(<<1,2,3>>, ctx)
<<3>>
```

In this case, `<<1,2,3>>` is intended to be an obviously incorrect header block. According to the ExDoc for the function, it should be returning either `{:ok, state, headers}` or `{:error, :decode_error}` (obviously, the latter would apply in this case). Is this return value unexpected or simply undocumented?

**Comment by OleMchls** [comment] 2021-09-22 20:25
Hey @mtrudel  thanks for the report and your patience. I've investigated the issue and while tricky I found the cause and just pushed a fix.

**Closed** 2021-09-22 20:24 UTC

**Comment by OleMchls** [comment] 2021-09-22 20:28
3.0.1 has just been released including the fix

**Comment by mtrudel** [comment] 2021-09-22 20:39
Bueno! Thanks!
